<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Doccomercial extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Doccomercial_model');
    } 

    /*
     * Listing of doccomercial
     */
    function index()
    {
        $data['doccomercial'] = $this->Doccomercial_model->get_all_doccomercial();
        
        $data['_view'] = 'doccomercial/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new doccomercial
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'inscripcion' => $this->input->post('inscripcion'),
				'inscripcionobs' => $this->input->post('inscripcionobs'),
				'inscripcionok' => $this->input->post('inscripcionok'),
				'balance' => $this->input->post('balance'),
				'balanceobs' => $this->input->post('balanceobs'),
				'balanceok' => $this->input->post('balanceok'),
				'refbancarias' => $this->input->post('refbancarias'),
				'refbancariasobs' => $this->input->post('refbancariasobs'),
				'refbancariasok' => $this->input->post('refbancariasok'),
				'antecedentes' => $this->input->post('antecedentes'),
				'antecedentesobs' => $this->input->post('antecedentesobs'),
				'antecedentesok' => $this->input->post('antecedentesok'),
				'refcomerciales' => $this->input->post('refcomerciales'),
				'refcomercialesobs' => $this->input->post('refcomercialesobs'),
				'refcomercialesok' => $this->input->post('refcomercialesok'),
				'contastanciaiibb' => $this->input->post('contastanciaiibb'),
				'constanciaiibbobs' => $this->input->post('constanciaiibbobs'),
				'constanciaiibbok' => $this->input->post('constanciaiibbok'),
				'infotecnica' => $this->input->post('infotecnica'),
				'infotecnicaobs' => $this->input->post('infotecnicaobs'),
				'infotecnicaok' => $this->input->post('infotecnicaok'),
				'autoevaluacion' => $this->input->post('autoevaluacion'),
				'autoevaluacionobs' => $this->input->post('autoevaluacionobs'),
				'autoevaluacionok' => $this->input->post('autoevaluacionok'),
				'constmonotirbuto' => $this->input->post('constmonotirbuto'),
				'constmonotributoobs' => $this->input->post('constmonotributoobs'),
				'constmonotributook' => $this->input->post('constmonotributook'),
				'titutlo' => $this->input->post('titutlo'),
				'tituloobs' => $this->input->post('tituloobs'),
				'titulook' => $this->input->post('titulook'),
				'matricula' => $this->input->post('matricula'),
				'matriculaobs' => $this->input->post('matriculaobs'),
				'matriculaok' => $this->input->post('matriculaok'),
				'antecedentesmono' => $this->input->post('antecedentesmono'),
				'antecedentesmonoobs' => $this->input->post('antecedentesmonoobs'),
				'antecedentesmonook' => $this->input->post('antecedentesmonook'),
				'refcomercialesmono' => $this->input->post('refcomercialesmono'),
				'refcomercialesmonoobs' => $this->input->post('refcomercialesmonoobs'),
				'refcomercialesmonook' => $this->input->post('refcomercialesmonook'),
				'refbancariasmono' => $this->input->post('refbancariasmono'),
				'refbancariasmonoobs' => $this->input->post('refbancariasmonoobs'),
				'refbancariasmonook' => $this->input->post('refbancariasmonook'),
				'completo' => $this->input->post('completo'),
				'aprobado' => $this->input->post('aprobado'),
				'idproveedor' => $this->input->post('idproveedor'),
				'contratosocial' => $this->input->post('contratosocial'),
				'contratosocialobs' => $this->input->post('contratosocialobs'),
				'contratosocialok' => $this->input->post('contratosocialok'),
            );
            
            $doccomercial_id = $this->Doccomercial_model->add_doccomercial($params);
            redirect('proveedores', 'refresh');
        }
        else
        {            
            $data['_view'] = 'doccomercial/add';
            $this->load->view('template/header',$data);
            $this->load->view('layouts/main');
        }
    }  

    /*
     * Editing a doccomercial
     */
    function edit($iddoccomercial)
    {   
        // check if the doccomercial exists before trying to edit it
        $data['doccomercial'] = $this->Doccomercial_model->get_doccomercial($iddoccomercial);
        
        if(isset($data['doccomercial']['iddoccomercial']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'inscripcion' => $this->input->post('inscripcion'),
					'inscripcionobs' => $this->input->post('inscripcionobs'),
					'inscripcionok' => $this->input->post('inscripcionok'),
					'balance' => $this->input->post('balance'),
					'balanceobs' => $this->input->post('balanceobs'),
					'balanceok' => $this->input->post('balanceok'),
					'refbancarias' => $this->input->post('refbancarias'),
					'refbancariasobs' => $this->input->post('refbancariasobs'),
					'refbancariasok' => $this->input->post('refbancariasok'),
					'antecedentes' => $this->input->post('antecedentes'),
					'antecedentesobs' => $this->input->post('antecedentesobs'),
					'antecedentesok' => $this->input->post('antecedentesok'),
					'refcomerciales' => $this->input->post('refcomerciales'),
					'refcomercialesobs' => $this->input->post('refcomercialesobs'),
					'refcomercialesok' => $this->input->post('refcomercialesok'),
					'contastanciaiibb' => $this->input->post('contastanciaiibb'),
					'constanciaiibbobs' => $this->input->post('constanciaiibbobs'),
					'constanciaiibbok' => $this->input->post('constanciaiibbok'),
					'infotecnica' => $this->input->post('infotecnica'),
					'infotecnicaobs' => $this->input->post('infotecnicaobs'),
					'infotecnicaok' => $this->input->post('infotecnicaok'),
					'autoevaluacion' => $this->input->post('autoevaluacion'),
					'autoevaluacionobs' => $this->input->post('autoevaluacionobs'),
					'autoevaluacionok' => $this->input->post('autoevaluacionok'),
					'constmonotirbuto' => $this->input->post('constmonotirbuto'),
					'constmonotributoobs' => $this->input->post('constmonotributoobs'),
					'constmonotributook' => $this->input->post('constmonotributook'),
					'titutlo' => $this->input->post('titutlo'),
					'tituloobs' => $this->input->post('tituloobs'),
					'titulook' => $this->input->post('titulook'),
					'matricula' => $this->input->post('matricula'),
					'matriculaobs' => $this->input->post('matriculaobs'),
					'matriculaok' => $this->input->post('matriculaok'),
					'antecedentesmono' => $this->input->post('antecedentesmono'),
					'antecedentesmonoobs' => $this->input->post('antecedentesmonoobs'),
					'antecedentesmonook' => $this->input->post('antecedentesmonook'),
					'refcomercialesmono' => $this->input->post('refcomercialesmono'),
					'refcomercialesmonoobs' => $this->input->post('refcomercialesmonoobs'),
					'refcomercialesmonook' => $this->input->post('refcomercialesmonook'),
					'refbancariasmono' => $this->input->post('refbancariasmono'),
					'refbancariasmonoobs' => $this->input->post('refbancariasmonoobs'),
					'refbancariasmonook' => $this->input->post('refbancariasmonook'),
					'completo' => $this->input->post('completo'),
					'aprobado' => $this->input->post('aprobado'),
					'idproveedor' => $this->input->post('idproveedor'),
					'contratosocial' => $this->input->post('contratosocial'),
					'contratosocialobs' => $this->input->post('contratosocialobs'),
					'contratosocialok' => $this->input->post('contratosocialok'),
                );

                $this->Doccomercial_model->update_doccomercial($iddoccomercial,$params);            
                redirect('proveedores', 'refresh');
            }
            else
            {
                $data['_view'] = 'doccomercial/edit';
                $this->load->view('template/header',$data);
                $this->load->view('layouts/main');
            }
        }
        else
            show_error('The doccomercial you are trying to edit does not exist.');
    } 

    
    
}
