<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Docpagos extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Docpagos_model');
    }  

    /*
     * Editing a doccomercial
     */
    function edit($iddocpagos)
    {   
        // check if the doccomercial exists before trying to edit it
        $data['docpagos'] = $this->Docpagos_model->get_docpagos($iddocpagos);
        
        if(isset($data['docpagos']['iddocpagos']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idproveedor' => $this->input->post('idproveedor'),
                );

                $this->docpagos_model->update_docpagos($iddocpagos,$params);            
                redirect('proveedores', 'refresh');
            }
            else
            {
                $data['_view'] = 'docpagos/edit';
                $data['titulacion'] = 'Documentación Para Pagos';
                $this->load->view('template/header',$data);
                $this->load->view('layouts/main');
            }
        }
        else
            show_error('The doccomercial you are trying to edit does not exist.');
    }
}
