<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Proveedor extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Proveedore_model');
    }

    /*
     * Adding a new proveedor
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('empresa','Empresa','required');
		$this->form_validation->set_rules('apellidos','Apellidos','required');
		$this->form_validation->set_rules('nombres','Nombres','required');
		$this->form_validation->set_rules('mail','Mail','valid_email|required');
		$this->form_validation->set_rules('subrubro','Subrubro','required');
		$this->form_validation->set_rules('rubro','Rubro','required');
		$this->form_validation->set_rules('telefono','Telefono','required');
		$this->form_validation->set_rules('ciudad','Ciudad','required');
		$this->form_validation->set_rules('contacto','Contacto','required');
		$this->form_validation->set_rules('pass','Pass','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'rubro' => $this->input->post('rubro'),
				'pass' => MD5($this->input->post('pass')),
				'empresa' => $this->input->post('empresa'),
				'apellidos' => $this->input->post('apellidos'),
				'nombres' => $this->input->post('nombres'),
				'telefono' => $this->input->post('telefono'),
				'mail' => $this->input->post('mail'),
				'subrubro' => $this->input->post('subrubro'),
				'ciudad' => $this->input->post('ciudad'),
				'web' => $this->input->post('web'),
				'observaciones' => $this->input->post('observaciones'),
				'contacto' => $this->input->post('contacto'),
				'activo' => 1,
				'categoria' => $this->input->post('categoria'),
				'condicion' => $this->input->post('condicion'),
				'empleador' => $this->input->post('empleador'),
				'tipo' => $this->input->post('tipo')
            );
            
			$proveedor_id = $this->Proveedore_model->add_proveedor($params);
			$vv=$proveedor_id;
			if ($proveedor_id=!NULL){
				$formulariossale = $this->Proveedore_model->add_formularios($vv);
			}
			

            redirect('login');
        }
        else
        {            
			$data['titulacion']="Alta Proveedor";
            $data['_view'] = 'proveedore/add';
            $this->load->view('template/header',$data);
            $this->load->view('layouts/main');
        }
    }  

    /*
     * Editing a proveedor
     */
    function edit($idproveedor)
    {   
        // check if the proveedor exists before trying to edit it
        $data['proveedor'] = $this->Proveedore_model->get_proveedor($idproveedor);
        
        if(isset($data['proveedor']['idproveedor']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('empresa','Empresa','required');
			$this->form_validation->set_rules('apellidos','Apellidos','required');
			$this->form_validation->set_rules('nombres','Nombres','required');
			$this->form_validation->set_rules('mail','Mail','valid_email|required');
			$this->form_validation->set_rules('subrubro','Subrubro','required');
			$this->form_validation->set_rules('rubro','Rubro','required');
			$this->form_validation->set_rules('telefono','Telefono','required');
			$this->form_validation->set_rules('ciudad','Ciudad','required');
			$this->form_validation->set_rules('web','Web','required');
			$this->form_validation->set_rules('contacto','Contacto','required');
			$this->form_validation->set_rules('pass','Pass','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'rubro' => $this->input->post('rubro'),
					'pass' => $this->input->post('pass'),
					'empresa' => $this->input->post('empresa'),
					'apellidos' => $this->input->post('apellidos'),
					'nombres' => $this->input->post('nombres'),
					'telefono' => $this->input->post('telefono'),
					'mail' => $this->input->post('mail'),
					'subrubro' => $this->input->post('subrubro'),
					'ciudad' => $this->input->post('ciudad'),
					'web' => $this->input->post('web'),
					'observaciones' => $this->input->post('observaciones'),
					'contacto' => $this->input->post('contacto'),
					'activo' => $this->input->post('activo'),
					'categoria' => $this->input->post('categoria'),
                );

                $this->Proveedore_model->update_proveedor($idproveedor,$params);            
                redirect('default_controller');
            }
            else
            {
				$data['titulacion']="Modificacion Proveedor";
                $data['_view'] = 'proveedore/edit';
                $this->load->view('template/header',$data);
            	$this->load->view('layouts/main');
            }
        }
        else
            show_error('The proveedor you are trying to edit does not exist.');
    }
}
