<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Doccomercial_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get doccomercial by iddoccomercial
     */
    function get_doccomercial($iddoccomercial)
    {
        return $this->db->get_where('doccomercial',array('iddoccomercial'=>$iddoccomercial))->row_array();
    }
        
    /*
     * Get all doccomercial
     */
    function get_all_doccomercial()
    {
        $this->db->order_by('iddoccomercial', 'desc');
        return $this->db->get('doccomercial')->result_array();
    }
        
    function get_doccomercial_idusuario($idproveedor)
    {
        return $this->db->get_where('doccomercial',array('idproveedor'=>$idproveedor))->row_array();;
    }

    /*
     * function to add new doccomercial
     */
    function add_doccomercial($params)
    {
        $this->db->insert('doccomercial',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update doccomercial
     */
    function update_doccomercial($iddoccomercial,$params)
    {
        $this->db->where('iddoccomercial',$iddoccomercial);
        return $this->db->update('doccomercial',$params);
    }
    
    /*
     * function to delete doccomercial
     */
    function delete_doccomercial($iddoccomercial)
    {
        return $this->db->delete('doccomercial',array('iddoccomercial'=>$iddoccomercial));
    }
}
