<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Formulariofyc_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get formulariofyc by idformulariofyc
     */
    function get_formulariofyc($idformulariofyc)
    {
        return $this->db->get_where('formulariofyc',array('idformulariofyc'=>$idformulariofyc))->row_array();
    }
        
    /*
     * Get all formulariofyc
     */
    function get_all_formulariofyc()
    {
        $this->db->order_by('idformulariofyc', 'desc');
        return $this->db->get('formulariofyc')->result_array();
    }
        
    /*
     * function to add new formulariofyc
     */
    function add_formulariofyc($params)
    {
        $this->db->insert('formulariofyc',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update formulariofyc
     */
    function update_formulariofyc($idformulariofyc,$params)
    {
        $this->db->where('idformulariofyc',$idformulariofyc);
        return $this->db->update('formulariofyc',$params);
    }
    
    /*
     * function to delete formulariofyc
     */
    function delete_formulariofyc($idformulariofyc)
    {
        return $this->db->delete('formulariofyc',array('idformulariofyc'=>$idformulariofyc));
    }
}
